2025-04-18 21:51:31,442 INFO    MainThread:2528943 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2025-04-18 21:51:31,442 INFO    MainThread:2528943 [wandb_setup.py:_flush():76] Configure stats pid to 2528943
2025-04-18 21:51:31,442 INFO    MainThread:2528943 [wandb_setup.py:_flush():76] Loading settings from /home/goufandi/.config/wandb/settings
2025-04-18 21:51:31,442 INFO    MainThread:2528943 [wandb_setup.py:_flush():76] Loading settings from /data/goufandi_space/Projects/GS-MARL/gsmarl/scripts/wandb/settings
2025-04-18 21:51:31,442 INFO    MainThread:2528943 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-04-18 21:51:31,442 INFO    MainThread:2528943 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-04-18 21:51:31,442 INFO    MainThread:2528943 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'gsmarl/scripts/train_mpe.py', 'program_abspath': '/data/goufandi_space/Projects/GS-MARL/gsmarl/scripts/train_mpe.py', 'program': 'train_mpe.py'}
2025-04-18 21:51:31,442 INFO    MainThread:2528943 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-04-18 21:51:31,443 INFO    MainThread:2528943 [wandb_init.py:_log_setup():521] Logging user logs to /data/goufandi_space/Projects/GS-MARL/gsmarl/results/MPE/exp2/gsmarl/test/wandb/run-20250418_215131-o7s055py/logs/debug.log
2025-04-18 21:51:31,443 INFO    MainThread:2528943 [wandb_init.py:_log_setup():522] Logging internal logs to /data/goufandi_space/Projects/GS-MARL/gsmarl/results/MPE/exp2/gsmarl/test/wandb/run-20250418_215131-o7s055py/logs/debug-internal.log
2025-04-18 21:51:31,443 INFO    MainThread:2528943 [wandb_init.py:init():561] calling init triggers
2025-04-18 21:51:31,443 INFO    MainThread:2528943 [wandb_init.py:init():569] wandb.init called with sweep_config: {}
config: {'algorithm_name': 'gsmarl', 'seed': 1, 'device': 'cuda:3', 'cuda_deterministic': True, 'n_training_threads': 128, 'n_rollout_threads': 8, 'n_render_rollout_threads': 1, 'num_env_steps': 10000000.0, 'scenario_name': 'exp2', 'num_obstacles': 3, 'num_agents': 3, 'num_landmarks': 3, 'restore_model': True, 'parameter_share': True, 'user_name': '431', 'wandb_project_name': 'EXP', 'experiment_name': 'test', 'use_wandb': True, 'env_name': 'MPE', 'episode_length': 100, 'hidden_size': 64, 'use_popart': True, 'use_valuenorm': True, 'use_orthogonal': True, 'gain': 0.01, 'gnn_num_heads': 3, 'use_naive_recurrent_policy': False, 'use_recurrent_policy': False, 'recurrent_N': 1, 'data_chunk_length': 10, 'lr': 0.007, 'critic_lr': 0.007, 'opti_eps': 1e-05, 'weight_decay': 0, 'kl_threshold': 0.05, 'safety_bound': 1, 'ls_step': 10, 'accept_ratio': 0.5, 'EPS': 1e-08, 'use_clipped_value_loss': True, 'clip_param': 0.2, 'value_loss_coef': 1, 'num_mini_batch': 2, 'use_max_grad_norm': True, 'max_grad_norm': 10.0, 'use_gae': True, 'gae_lambda': 0.95, 'gamma': 0.99, 'use_proper_time_limits': False, 'use_huber_loss': True, 'use_value_active_masks': True, 'use_policy_active_masks': True, 'huber_delta': 10.0, 'line_search_fraction': 0.5, 'fraction_coef': 0.05, 'use_linear_lr_decay': False, 'save_interval': 1, 'log_interval': 5, 'save_gifs': True, 'use_render': False, 'render_episodes': 1, 'ifi': 0.1, 'model_dir': 'xxx'}
2025-04-18 21:51:31,443 INFO    MainThread:2528943 [wandb_init.py:init():611] starting backend
2025-04-18 21:51:31,443 INFO    MainThread:2528943 [wandb_init.py:init():615] setting up manager
2025-04-18 21:51:31,454 INFO    MainThread:2528943 [backend.py:_multiprocessing_setup():107] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-18 21:51:31,480 INFO    MainThread:2528943 [wandb_init.py:init():623] backend started and connected
2025-04-18 21:51:31,502 INFO    MainThread:2528943 [wandb_init.py:init():715] updated telemetry
2025-04-18 21:51:31,521 INFO    MainThread:2528943 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2025-04-18 21:51:32,250 ERROR   MainThread:2528943 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-04-18 21:51:32,507 ERROR   MainThread:2528943 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/data/goufandi_space/Software/anaconda3/envs/gs_marl/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/data/goufandi_space/Software/anaconda3/envs/gs_marl/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-04-18 21:51:33,511 WARNING MsgRouterThr:2528943 [router.py:message_loop():77] message_loop has been closed
